import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {chromium} from 'playwright';import {ProfileTransfer,TRANSFER_FORMAT,parseTransfer,sessionForTransfer,restoreSession,captureSession} from './profile-transfer.mjs';import {ProfileImporter} from './profile-import.mjs';import {ProfileManager} from './profile-manager.mjs';import {Store} from './store.mjs';import {AUTO_DEFAULTS} from '../extension/auto-runner.js';
const cookie={name:'fixture_session',value:'dummy-session-value',domain:'.threads.com',path:'/',expires:-1,httpOnly:true,secure:true,sameSite:'Lax'},session={cookies:[cookie],origins:[{origin:'https://www.threads.com',localStorage:[{name:'fixture-local',value:'dummy-local-value'}]}]};
const file={format:TRANSFER_FORMAT,version:1,profiles:[{id:'source-a',name:'Fixture A',proxy:'fixture:80:user:pass',browserVersion:'152.0.0.0',session}]};
test('session files allow only Meta cookies/storage, validate before mutations and previews never expose cookie values',()=>{
 assert.deepEqual(parseTransfer(JSON.stringify(file))[0].session,session);assert.throws(()=>parseTransfer(JSON.stringify({...file,version:2})));assert.throws(()=>parseTransfer(JSON.stringify({...file,profiles:[{...file.profiles[0],id:'../escape'}]})));assert.throws(()=>parseTransfer(JSON.stringify({...file,profiles:[{...file.profiles[0],session:{cookies:[{...cookie,domain:'evil.example'}],origins:[]}}]})));
 const clean=sessionForTransfer({cookies:[cookie,{...cookie,domain:'.unrelated.example'}],origins:[...session.origins,{origin:'https://unrelated.example',localStorage:[]}]});assert.deepEqual(clean,session);
});
test('cross-machine restore creates one destination profile, retains pending retry, and never starts automation',async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gpm-transfer-')),store=await new Store(dir).load(),calls=[];let created=0,failOnce=true;
 await store.set({settings:{profileId:'',model:'destination-model',prompt:'destination prompt',apiKey:'destination-key',gpmApi:'http://localhost:9495',cdp:'http://localhost:9222',runConfig:AUTO_DEFAULTS},profileMigrationDone:true});
 const manager=new ProfileManager(store,{workerFactory:(dir)=>({close:async()=>{},call:async(route,input)=>{calls.push(route);if(route==='settings'){const s=await new Store(dir).load();await s.set({settings:input});return {ok:true};}if(route==='profile-open')return {profileName:'Fixture A'};if(route==='profile-session-import'){assert.deepEqual(input.session,session);if(failOnce){failOnce=false;throw Error('fixture failure');}return {ok:true};}throw Error('Unexpected route '+route);}})});
 const api={list:async()=>[],create:async input=>{created++;assert.equal(input.rawProxy,'fixture:80:user:pass');return {id:'destination-b',name:'Fixture A',proxy:input.rawProxy};}},importer=new ProfileImporter(manager,{apiFactory:()=>api});
 try{const preview=await importer.preview({text:JSON.stringify(file)});assert.equal(preview.rows[0].message,'Tạo profile GPM mới và khôi phục phiên');assert.ok(!JSON.stringify(preview).includes(cookie.value));assert.equal(created,0);
 const first=await importer.commit({token:preview.token,ids:['source-a']});assert.equal(first.results[0].status,'error');assert.equal(store.value.profileRegistry['destination-b'].transferPending,true);
 const retry=await importer.preview({text:JSON.stringify(file)});assert.equal(retry.rows[0].status,'ready');const success=await importer.commit({token:retry.token,ids:['source-a']});assert.equal(success.results[0].id,'destination-b');assert.equal(success.results[0].status,'imported');assert.equal(created,1);assert.equal(store.value.profileRegistry['destination-b'].transferPending,false);assert.equal(calls.includes('start'),false);
 const data=(await manager.profileStore('destination-b')).value;assert.equal(data.settings.model,'destination-model');assert.equal(JSON.stringify(data).includes(cookie.value),false);const again=await importer.preview({text:JSON.stringify(file)});assert.equal(again.rows[0].status,'existing');
 }finally{await manager.close();await fs.rm(dir,{recursive:true,force:true});}
});
test('real browser restores HttpOnly cookies and local storage into a fresh context without retaining the injection script',async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':process.platform==='win32'?'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe':'/usr/bin/google-chrome'),headless:true});
 try{const source=await browser.newContext();await source.route('**/*',route=>route.fulfill({contentType:'text/html',body:'<html>Fixture</html>'}));await source.addCookies([cookie]);const sourcePage=await source.newPage();await sourcePage.goto('https://www.threads.com/');await sourcePage.evaluate(()=>localStorage.setItem('fixture-local','dummy-local-value'));const exported=sessionForTransfer(await source.storageState());
 const target=await browser.newContext();await target.route('**/*',route=>route.fulfill({contentType:'text/html',body:'<html>Fixture</html>'}));await restoreSession(target,exported);assert.equal((await target.cookies('https://www.threads.com')).find(c=>c.name===cookie.name).value,cookie.value);const page=await target.newPage();await page.goto('https://www.threads.com/');assert.equal(await page.evaluate(()=>localStorage.getItem('fixture-local')),'dummy-local-value');await page.evaluate(()=>localStorage.setItem('fixture-local','updated'));await page.reload();assert.equal(await page.evaluate(()=>localStorage.getItem('fixture-local')),'updated');
 }finally{await browser.close();}
});
test('export captures only Meta session and proxy from the chosen GPM profile without tool keys or histories',async()=>{
 const manager={rows:()=>[{id:'a',name:'A'}],profileStore:async()=>({value:{settings:{gpmApi:'http://localhost:9495',apiKey:'do-not-export-key'},replyReceipts:{secret:'history'}}}),worker:()=>({call:async route=>{assert.equal(route,'profile-session-export');return session;}})};
 const transfer=new ProfileTransfer(manager,{apiFactory:()=>({call:async()=>({id:'a',name:'GPM A',raw_proxy:'proxy:80:user:pass',browser:{version:'152.0.0.0'}})})});const data=await transfer.export(['a']);assert.equal(data.format,TRANSFER_FORMAT);assert.equal(data.profiles[0].session.cookies[0].value,cookie.value);assert.equal(data.profiles[0].proxy,'proxy:80:user:pass');assert.equal(JSON.stringify(data).includes('do-not-export-key'),false);assert.equal(JSON.stringify(data).includes('history'),false);
});

test('capture includes local storage in pages opened before CDP attached',async()=>{
 const context={storageState:async()=>({cookies:[cookie],origins:[]}),pages:()=>[{url:()=> 'https://www.threads.com/',evaluate:async()=>session.origins[0]}]};assert.deepEqual(await captureSession(context),session);
});
