import {AUTO_DEFAULTS} from '../extension/auto-runner.js';
import http from 'node:http';
import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gpm-ui-')),port=14317;let browser,createPayload;let deletedMode;const mockGpm=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;let data=null;const url=new URL(req.url,'http://localhost');
 if(req.method==='POST'&&url.pathname==='/api/v1/profiles/create'){createPayload=JSON.parse(body);data={id:'created-fixture',name:createPayload.name,raw_proxy:createPayload.raw_proxy};}
 else if(url.pathname==='/api/v1/profiles/created-fixture'){data={id:'created-fixture',name:createPayload.name,raw_proxy:createPayload.raw_proxy};}
 else if(url.pathname==='/api/v1/profiles/update/created-fixture'){const update=JSON.parse(body);createPayload={...createPayload,...update};data={id:'created-fixture',name:update.name};}
 else if(url.pathname==='/api/v1/profiles/delete/created-fixture'){deletedMode=url.searchParams.get('mode');}
 else if(url.pathname!=='/api/v1/profiles/stop/created-fixture'){res.writeHead(404);res.end('{}');return;}
 res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({success:true,data}));});await new Promise(r=>mockGpm.listen(0,'127.0.0.1',r));const mockGpmBase='http://127.0.0.1:'+mockGpm.address().port;
await fs.writeFile(path.join(dir,'state.json'),JSON.stringify({settings:{cdp:'http://localhost:9222',gpmApi:mockGpmBase,profileId:'',proxy:'',apiKey:'',model:'cx/gpt-5.6-luna',prompt:await fs.readFile(new URL('../extension/default-prompt.txt',import.meta.url),'utf8'),runConfig:AUTO_DEFAULTS},profileMigrationDone:true,profileRegistry:{a:{id:'a',name:'Profile A',proxy:''},b:{id:'b',name:'Profile B',proxy:'fixture:80:user:pass'}}}));
for(const [id,sent] of [['a',25],['b',2]]){await fs.mkdir(path.join(dir,'profiles',id),{recursive:true});await fs.writeFile(path.join(dir,'profiles',id,'state.json'),JSON.stringify({settings:{profileId:id,profileName:id==='a'?'Profile A':'Profile B',gpmApi:mockGpmBase,cdp:'http://localhost:9222',proxy:id==='b'?'fixture:80:user:pass':'',model:'cx/gpt-5.6-luna',apiKey:'',prompt:'Fixture prompt',runConfig:AUTO_DEFAULTS},autoRun:{status:'stopped',stats:{sent},events:[{time:'2026-10-07T01:00:00Z',message:'Nhật ký riêng '+id}]},replyReceipts:{post:{state:'sent_unverified',created_at:'2026-10-07T01:00:00Z',post_url:'https://www.threads.com/@fixture/post/'+id}}}));}
const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('.',import.meta.url),env:{...process.env,PORT:String(port),GPM_TOOL_DATA:dir},stdio:['ignore','pipe','pipe']});
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server startup timeout')),10000);child.stdout.on('data',d=>{if(d.toString().includes('GPM tool UI')){clearTimeout(timer);resolve();}});child.once('exit',code=>reject(Error('Server exited '+code)));});
 browser=await chromium.launch({executablePath:process.env.TEST_CHROME||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':process.platform==='win32'?'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe':'/usr/bin/google-chrome'),headless:true});const page=await browser.newPage({viewport:{width:1200,height:1000}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+port);await page.waitForFunction(()=>document.getElementById('prompt').value.length>100);
 assert.match(await page.locator('#settings-target').innerText(),/Tất cả 2 profile/);assert.equal(await page.locator('#open-selected').isDisabled(),true);assert.equal(await page.locator('#start-selected').isDisabled(),true);const cardA=page.locator('#profile-rows tr').filter({hasText:'Profile A'});await cardA.locator('.profile-name').click();assert.equal(await cardA.locator('input[type=checkbox]').isChecked(),true);assert.match(await page.locator('#selection-count').innerText(),/1 profile/);await cardA.getByRole('button',{name:'Xem log',exact:true}).click();assert.equal(await cardA.locator('input[type=checkbox]').isChecked(),true);await cardA.locator('.state-badge').click();assert.equal(await cardA.locator('input[type=checkbox]').isChecked(),false);await cardA.locator('input[type=checkbox]').check();assert.equal(await cardA.locator('input[type=checkbox]').isChecked(),true);await cardA.locator('input[type=checkbox]').uncheck();await page.locator('#close-profile-log').click();await page.locator('#restAverage').fill('60');assert.equal(await page.locator('#rest-range-preview').innerText(),'48–72 giây');await page.locator('#restAverage').fill('150');await page.locator('[data-profile-filter="running"]').click();assert.equal(await page.locator('#profile-rows tr').count(),0);assert.equal(await page.locator('#profiles-empty-panel').isVisible(),true);await page.locator('#clear-profile-filters').click();assert.equal(await page.locator('#profile-rows tr').count(),2);await page.locator('#profile-density').click();assert.equal(await page.locator('#profiles-panel').evaluate(e=>e.classList.contains('compact-profiles')),true);await page.locator('#profile-density').click();await page.screenshot({path:'/tmp/thread-ui-desktop.png'});await page.locator('#select-all-profiles').check();assert.match(await page.locator('#selection-count').innerText(),/2 profile/);await page.locator('#profile-search').fill('profile b');assert.equal(await page.locator('#profile-rows tr').count(),1);await page.locator('#profile-search').fill('');await page.locator('#select-all-profiles').uncheck();assert.equal(await page.locator('#selection-count').innerText(),'Bấm thẻ để chọn');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/thread-ui-mobile.png'});await page.setViewportSize({width:1200,height:1000});

 assert.match(await page.locator('#history').innerText(),/Profile A/);assert.match(await page.locator('#history').innerText(),/Profile B/);
 assert.match(await page.locator('#log').innerText(),/Profile A → .*Nhật ký riêng a/);assert.match(await page.locator('#log').innerText(),/Profile B → .*Nhật ký riêng b/);const chooseExisting=async()=>{await page.locator('#profile-add-toggle').click();await page.locator('#pick-gpm-profiles').click();};assert.equal(await page.locator('#profile-add-choices').isVisible(),false);const rows=page.locator('#profile-rows tr');assert.equal(await rows.count(),2);assert.match(await rows.nth(0).innerText(),/25 \/ 25/);assert.match(await rows.nth(1).innerText(),/2 \/ 25/);assert.match(await rows.nth(1).innerText(),/fixture:80:user:pass/);
 let selectedIds;await page.route('**/api/profiles-start',async route=>{selectedIds=route.request().postDataJSON().ids;await route.fulfill({json:{results:selectedIds.map(id=>({id,ok:true}))}});});
 await page.getByRole('checkbox',{name:'Chọn Profile A',exact:true}).check();await page.getByRole('checkbox',{name:'Chọn Profile B',exact:true}).check();await page.locator('#start-selected').click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent.includes('Profile B: đã xử lý'));assert.deepEqual(selectedIds,['a','b']);
 let closedIds,closedId,openedId;const openedIds=[];
 await page.route('**/api/profiles-close',async route=>{closedIds=route.request().postDataJSON().ids;await route.fulfill({json:{results:closedIds.map(id=>({id,ok:true}))}});});
 await page.route('**/api/profile-close',async route=>{closedId=route.request().postDataJSON().id;await route.fulfill({json:{ok:true}});});
 await page.route('**/api/profile-open',async route=>{openedId=route.request().postDataJSON().profileId;openedIds.push(openedId);await route.fulfill({json:{ok:true,profileName:'Profile B'}});});
 await page.getByRole('checkbox',{name:'Chọn Profile A',exact:true}).uncheck();await page.locator('#stop-selected').click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent.includes('Profile B: đã dừng và đóng profile'));assert.deepEqual(closedIds,['b']);await page.getByRole('checkbox',{name:'Chọn Profile B',exact:true}).uncheck();
 for(const name of ['Chạy','Dừng phiên','Đóng profile'])assert.equal(await rows.getByRole('button',{name,exact:true}).count(),0);
 await rows.nth(1).getByRole('button',{name:'Dừng profile',exact:true}).click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent==='Đã dừng và đóng Profile B.');assert.equal(closedId,'b');
 const startsBeforeOpen=selectedIds;await page.getByRole('checkbox',{name:'Chọn Profile A',exact:true}).check();await page.getByRole('checkbox',{name:'Chọn Profile B',exact:true}).check();await page.locator('#open-selected').click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent.includes('Profile B: đã mở trình duyệt'));assert.deepEqual(openedIds,['a','b']);assert.equal(selectedIds,startsBeforeOpen);
 await page.waitForFunction(()=>!document.getElementById('open-selected').disabled);await page.unroute('**/api/profile-open');let releaseOpen;const openGate=new Promise(resolve=>{releaseOpen=resolve;});const cancelledOpenIds=[];await page.route('**/api/profile-open',async route=>{cancelledOpenIds.push(route.request().postDataJSON().profileId);await openGate;await route.fulfill({json:{ok:true,profileName:'Profile A',cancelled:true}});});await page.locator('#open-selected').click();await page.waitForFunction(()=>!document.getElementById('loading-status').hidden);assert.equal(await page.locator('#open-selected').isDisabled(),true);assert.equal(await page.locator('#stop-selected').isEnabled(),true);await page.locator('#stop-selected').click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent.includes('Profile B: đã dừng'));releaseOpen();await page.waitForFunction(()=>document.getElementById('loading-status').hidden);assert.deepEqual(cancelledOpenIds,['a']);assert.equal(selectedIds,startsBeforeOpen);await page.unroute('**/api/profile-open');await page.route('**/api/profile-open',async route=>{openedId=route.request().postDataJSON().profileId;await route.fulfill({json:{ok:true,profileName:'Profile B'}});});await page.locator('#clear-selection').click();await page.locator('#prompt').fill('Nháp khi mở');await rows.nth(1).getByRole('button',{name:'Mở',exact:true}).click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent.includes('Đã mở Profile B trong GPM'));assert.equal(openedId,'b');assert.equal(selectedIds,startsBeforeOpen);assert.equal(await page.locator('#prompt').inputValue(),'Nháp khi mở');
 await rows.nth(1).getByRole('button',{name:'Xem log'}).click();assert.equal(await page.locator('#profile-log-panel').isVisible(),true);assert.equal(await page.locator('#profile-log-title').innerText(),'Nhật ký · Profile B');assert.match(await page.locator('#profile-log').innerText(),/Nhật ký riêng b/);assert.ok(!(await page.locator('#profile-log').innerText()).includes('Nhật ký riêng a'));assert.match(await page.locator('#log').innerText(),/Nhật ký riêng a/);await chooseExisting();assert.match(await page.locator('#profile-log').innerText(),/Nhật ký riêng b/);await page.locator('#close-profile-log').click();assert.equal(await page.locator('#profile-log-panel').isVisible(),false);
 assert.equal(await page.locator('#idle-engagement').isChecked(),true);await page.locator('#idle-engagement').uncheck();
 await page.waitForFunction(()=>!document.getElementById('pick-gpm-profiles').disabled);let staleToken=true,settingsRequests=0;
 await page.route('**/api/state',async route=>{if(!staleToken)return route.continue();staleToken=false;const response=await route.fetch(),data=await response.json();await route.fulfill({json:{...data,token:'stale-dashboard-token'}});});
 await page.route('**/api/settings',async route=>{settingsRequests++;await route.continue();});
 await Promise.all([page.waitForResponse(async r=>r.url().endsWith('/api/state')&&(await r.json()).token==='stale-dashboard-token'),chooseExisting()]);
 await page.locator('#prompt').fill('Prompt kiểm tra đã sửa');await page.locator('#key').fill('test-secret-ui');await page.locator('#timing-advanced > summary').click();await page.locator('#step').fill('3');await page.locator('#search').fill('45');await page.locator('#idle').uncheck();await page.locator('#save').click();await page.getByText('Đã áp dụng cho 2 profile · model cx/gpt-5.6-luna · dùng từ bước tiếp theo.',{exact:true}).waitFor();await page.reload();await page.waitForFunction(()=>document.getElementById('prompt').value==='Prompt kiểm tra đã sửa');
 assert.equal(await page.locator('#step').inputValue(),'3');assert.equal(await page.locator('#search').inputValue(),'45');assert.equal(await page.locator('#idle').isChecked(),false);
 assert.equal(await page.locator('#idle-engagement').isChecked(),false);
 assert.equal(settingsRequests,2);assert.ok(!(await page.locator('#error').innerText()).includes('Invalid origin/token'));await page.unroute('**/api/state');await page.unroute('**/api/settings');
 const snapshot=await page.evaluate(()=>fetch('/api/state').then(r=>r.text()));assert.ok(!snapshot.includes('test-secret-ui'));assert.equal(await page.locator('#gpmApi, #cdp, #profileId, #proxy, #profile-open, #connect').count(),0);const unauthorized=await fetch('http://127.0.0.1:'+port+'/api/stop',{method:'POST',body:'{}'});assert.equal(unauthorized.status,403);assert.deepEqual(errors,[]);
 const fresh=JSON.parse(snapshot);const livePromise=fetch('http://127.0.0.1:'+port+'/api/events').then(async r=>{const reader=r.body.getReader();const first=await reader.read();await reader.cancel();return new TextDecoder().decode(first.value);});assert.match(await livePromise,/counts/);
 await page.locator('#prompt').fill('Nháp chưa lưu');await chooseExisting();assert.equal(await page.locator('#prompt').inputValue(),'Nháp chưa lưu');assert.equal(await page.locator('#start, #stop, #refresh, #export, #session-count, #status').count(),0);
 const history=await page.evaluate(()=>fetch('/api/history').then(r=>r.text()));assert.ok(!history.includes('test-secret-ui'));assert.ok(!history.includes('settings'));
 await page.locator('#save').click();await page.waitForFunction(async base=>(await fetch('/api/state').then(r=>r.json())).settings.gpmApi===base,mockGpmBase);
 await page.locator('#prompt').fill('Nháp giữ nguyên khi tạo profile');await page.locator('#profile-add-toggle').click();await page.locator('#add-profile').click();assert.equal(await page.locator('#new-profile-panel').getAttribute('open'),'');await page.locator('#new-profile-name').fill('Profile mới');await page.locator('#new-profile-proxy').fill('fixture:8080:newuser:newpass');await page.locator('#new-profile-version').fill('152.0.7977.140');await page.locator('#create-profile').click();await page.waitForFunction(()=>document.getElementById('create-profile-status').textContent.includes('Đã tạo Profile mới'));
 await page.waitForFunction(()=>document.getElementById('profile-rows').innerText.includes('Profile mới'));assert.equal((await page.evaluate(()=>fetch('/api/state').then(r=>r.json()))).settings.profileId,'');assert.match(await page.locator('#profile-rows').innerText(),/fixture:8080:newuser:newpass/);assert.equal(await page.getByRole('checkbox',{name:'Chọn Profile mới',exact:true}).isChecked(),true);assert.equal(await page.locator('#new-profile-panel').isVisible(),false);assert.match(await page.locator('#profile-next-title').innerText(),/Đã tạo Profile mới/);assert.equal(await page.locator('#profile-rows input:checked').count(),1);assert.equal(createPayload.raw_proxy,'fixture:8080:newuser:newpass');assert.equal(createPayload.browser_type,1);assert.equal(await page.locator('#prompt').inputValue(),'Nháp giữ nguyên khi tạo profile');assert.equal(await page.locator('#dirty').innerText(),'Có thay đổi chưa lưu');await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('dirty').textContent==='Đã lưu cấu hình');await page.locator('#profile-rows tr').filter({hasText:'Profile mới'}).getByRole('button',{name:'Cài đặt',exact:true}).click();assert.equal(await page.locator('#settings-profile').innerText(),'· Dùng chung');assert.deepEqual(errors,[]);
 await page.locator('#profile-rows tr').filter({hasText:'Profile mới'}).getByRole('button',{name:'Sửa profile',exact:true}).click();await page.locator('#edit-profile-name').fill('Profile đổi tên');await page.locator('#edit-profile-proxy').fill('');await page.locator('#edit-profile-save').click();await page.waitForFunction(()=>document.getElementById('edit-profile-status').textContent==='Đã lưu Profile đổi tên.');assert.equal(createPayload.raw_proxy,'');await page.waitForFunction(()=>document.getElementById('profile-rows').innerText.includes('Profile đổi tên'));assert.match(await page.locator('#profile-rows tr').filter({hasText:'Profile đổi tên'}).innerText(),/Không proxy/);assert.match(await page.locator('#settings-target').innerText(),/Tất cả 3 profile/);
 page.once('dialog',dialog=>dialog.accept());await page.locator('#profile-rows tr').filter({hasText:'Profile đổi tên'}).getByRole('button',{name:'Xoá',exact:true}).click();await page.waitForFunction(()=>document.getElementById('batch-status').textContent.includes('Đã chuyển Profile đổi tên'));assert.equal(deletedMode,'soft');await page.waitForFunction(()=>document.querySelectorAll('#profile-rows tr').length===2);assert.equal(await page.locator('#edit-profile-panel').isVisible(),false);
 await page.locator('#profile-add-toggle').click();await page.locator('#add-profile').click();await page.locator('#new-profile-name').fill('');await page.locator('#create-profile').click();await page.waitForFunction(()=>document.getElementById('create-profile-status').textContent.includes('Không tạo được profile'));await page.waitForFunction(()=>!document.getElementById('create-profile').disabled);assert.equal(await page.locator('#create-profile').isEnabled(),true);assert.equal(await rows.count(),2);
 await page.getByRole('checkbox',{name:'Chọn Profile A',exact:true}).check();let releaseModels;const modelsGate=new Promise(resolve=>{releaseModels=resolve;});await page.route('**/api/models',async route=>{await modelsGate;await route.fulfill({json:{models:['fixture/model']}});});await page.locator('#load-models').click();await page.waitForFunction(()=>!document.getElementById('loading-status').hidden);assert.match(await page.locator('#loading-message').innerText(),/danh sách model/);assert.equal(await page.locator('#load-models').getAttribute('aria-busy'),'true');assert.equal(await page.locator('#stop-selected').isEnabled(),true);releaseModels();await page.waitForFunction(()=>document.getElementById('loading-status').hidden);assert.equal(await page.locator('#load-models').getAttribute('aria-busy'),null);await page.unroute('**/api/models');
 await page.route('**/api/models',route=>route.fulfill({status:500,json:{error:'Fixture API failure'}}));await page.locator('#load-models').click();await page.waitForFunction(()=>document.getElementById('error').textContent==='Fixture API failure');await page.waitForFunction(()=>document.getElementById('loading-status').hidden);assert.equal(await page.locator('#load-models').isEnabled(),true);await page.unroute('**/api/models');

 let releaseUpdate,installCalls=0,pretendRunning=false;const updateGate=new Promise(resolve=>{releaseUpdate=resolve;});const updateInfo={currentVersion:'0.3.7',repository:'fixture/tool',installSupported:true,available:true,latestVersion:'0.3.8'};
 await page.route('**/api/update-status',route=>route.fulfill({json:updateInfo}));await page.route('**/api/update-check',async route=>{await updateGate;await route.fulfill({json:updateInfo});});
 await page.route('**/api/update-install',route=>{installCalls++;return route.fulfill({status:400,json:{error:'Fixture checksum mismatch'}});});
 await page.route('**/api/state',async route=>{const r=await route.fetch(),v=await r.json();if(pretendRunning)v.profiles[0].view.state.status='running';await route.fulfill({json:v});});
 await page.reload();await page.waitForFunction(()=>document.getElementById('check-update').disabled===false&&document.getElementById('dirty').dataset.state==='saved');
 await page.locator('#check-update').click();assert.equal(await page.locator('#check-update').isDisabled(),true);assert(await page.locator('#check-update').evaluate(e=>e.classList.contains('is-loading')));releaseUpdate();await page.waitForFunction(()=>!document.getElementById('check-update').disabled);assert.match(await page.locator('#update-status').innerText(),/0.3.8/);
 pretendRunning=true;await page.locator('#install-update').click();await page.waitForFunction(()=>document.getElementById('update-status').textContent.includes('Dừng các profile'));assert.equal(installCalls,0);pretendRunning=false;
 await page.locator('#prompt').fill('Update draft fixture');await page.locator('#install-update').click();await page.waitForFunction(()=>document.getElementById('update-status').textContent.includes('Lưu các cài đặt'));assert.equal(installCalls,0);
 await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('dirty').dataset.state==='saved');await page.locator('#install-update').click();await page.waitForFunction(()=>document.getElementById('update-status').textContent==='Fixture checksum mismatch');assert.equal(installCalls,1);assert.equal(await page.locator('#install-update').isEnabled(),true);assert.deepEqual(errors,[]);
 await page.locator('#settings-panel').screenshot({path:'/tmp/thread-settings-ux.png'});await page.screenshot({path:'/tmp/gpm-tool-ui.png',fullPage:true});console.log('UI smoke passed: prompt/settings, key redaction, protection, update loading/guards/errors; no JS errors.');
}finally{if(browser)await browser.close();child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));await fs.rm(dir,{recursive:true,force:true});mockGpm.closeAllConnections();await new Promise(r=>mockGpm.close(r));}
